<?php

namespace App\Http\Controllers;

use App\Enums\GradeUnitType;
use App\Enums\TimeFormatType;
use App\Models\Preferences;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Illuminate\Validation\Rules;

class PreferenceController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //manage user preferences
        $preferences = DB::table('preferences')->get();
        
        //return preferences as json response, for management in frontend
        return response()->json($preferences);
    }

    //Function create() generated by default inside the model of Preferences
    
    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //Search for the preferences by user id...
        $preferences = Preferences::firstOrCreate(
            ['user_id' => Auth::id()],
            [
                'temperature_unit' => GradeUnitType::Farenheight->value,
                'time_format' => TimeFormatType::TwelveHours->value,
            ]
        );
        //return preferences as json response, for management in frontend
        return response()->json($preferences);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request)
    {
        //validate the incoming request data
        $request->validate([
            'temperature_unit' => 'required|string|in:°F,°C,°K',
            'time_format' => 'required|string|in:12H,24H',
        ]);

        //Find the preferences by user id and update them
        $preferences = Auth::user()->preferences;

        //first way to update
        $preferences->update([
            'temperature_unit' => $request->temperature_unit,
            'time_format' => $request->time_format,
        ]);

        //second way to update
        /*
        $preferences->temperature_unit = $request->input('temperature_unit');
        $preferences->time_format = $request->input('time_format');
        */

        return response()->json(['message' => 'Preferences updated successfully', 'preferences' => $preferences]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}